// Code generated by Elsa. DO NOT EDIT.

//go:generate go run -mod=mod go.risoftinc.com/elsa/cmd/elsa gen
//go:build !elsabuild
// +build !elsabuild

package http

import (
	"go.risoftinc.com/elsa"

	config "go.risoftinc.com/xarch/config"
	entities "go.risoftinc.com/xarch/infrastructure/http/entities"
	gologger "go.risoftinc.com/gologger"
	goresponse "go.risoftinc.com/goresponse"
	gorm "gorm.io/gorm"
	healthHandler "go.risoftinc.com/xarch/infrastructure/http/handler/health"
	healthRepo "go.risoftinc.com/xarch/domain/repositories/health"
	healthSvc "go.risoftinc.com/xarch/domain/services/health"
	mid "go.risoftinc.com/xarch/infrastructure/http/middleware"
)

// This file generated from dep_manager.go at 2025-09-12T18:18:39+07:00

type Dependencies struct {
	Middlewares    mid.IContextMiddleware
	HealthHandlers healthHandler.IHealthHandler
}

func InitializeServices(db *gorm.DB, cfg config.Config, logger gologger.Logger, async *goresponse.AsyncConfigManager) *Dependencies {
	iHealthRepositories := healthRepo.NewHealthRepositories(db)
	iHealthServices := healthSvc.NewHealthService(logger, iHealthRepositories)
	iEntities := entities.NewEntities(async)
	iContextMiddleware := mid.NewContextMiddleware(logger)
	iHealthHandler := healthHandler.NewHealthHandlers(logger, iEntities, iHealthServices)

	elsa.Generate(iHealthRepositories, iHealthServices, iEntities, iContextMiddleware, iHealthHandler)
	return &Dependencies{
		Middlewares:    iContextMiddleware,
		HealthHandlers: iHealthHandler,
	}
}

