// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0--rc2
// source: infrastructure/grpc/proto/health.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for health metric
type HealthMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthMetricRequest) Reset() {
	*x = HealthMetricRequest{}
	mi := &file_infrastructure_grpc_proto_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthMetricRequest) ProtoMessage() {}

func (x *HealthMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_grpc_proto_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthMetricRequest.ProtoReflect.Descriptor instead.
func (*HealthMetricRequest) Descriptor() ([]byte, []int) {
	return file_infrastructure_grpc_proto_health_proto_rawDescGZIP(), []int{0}
}

// Response message for health metric
type HealthMetricResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Meta information
	Meta *Meta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Health metric data
	Data          *HealthMetricData `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthMetricResponse) Reset() {
	*x = HealthMetricResponse{}
	mi := &file_infrastructure_grpc_proto_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthMetricResponse) ProtoMessage() {}

func (x *HealthMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_grpc_proto_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthMetricResponse.ProtoReflect.Descriptor instead.
func (*HealthMetricResponse) Descriptor() ([]byte, []int) {
	return file_infrastructure_grpc_proto_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthMetricResponse) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *HealthMetricResponse) GetData() *HealthMetricData {
	if x != nil {
		return x.Data
	}
	return nil
}

// Meta information structure
type Meta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response message
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Error information (if any)
	Error         *string `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_infrastructure_grpc_proto_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_grpc_proto_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_infrastructure_grpc_proto_health_proto_rawDescGZIP(), []int{2}
}

func (x *Meta) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Meta) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// Health metric data structure
type HealthMetricData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status map for different services
	Status map[string]string `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Database information
	Database      *DatabaseInfo `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthMetricData) Reset() {
	*x = HealthMetricData{}
	mi := &file_infrastructure_grpc_proto_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthMetricData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthMetricData) ProtoMessage() {}

func (x *HealthMetricData) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_grpc_proto_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthMetricData.ProtoReflect.Descriptor instead.
func (*HealthMetricData) Descriptor() ([]byte, []int) {
	return file_infrastructure_grpc_proto_health_proto_rawDescGZIP(), []int{3}
}

func (x *HealthMetricData) GetStatus() map[string]string {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *HealthMetricData) GetDatabase() *DatabaseInfo {
	if x != nil {
		return x.Database
	}
	return nil
}

// Database information
type DatabaseInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Database stats or error message
	MaxOpenConnections int32 `protobuf:"varint,1,opt,name=MaxOpenConnections,proto3" json:"MaxOpenConnections,omitempty"`
	OpenConnections    int32 `protobuf:"varint,2,opt,name=OpenConnections,proto3" json:"OpenConnections,omitempty"`
	InUse              int32 `protobuf:"varint,3,opt,name=InUse,proto3" json:"InUse,omitempty"`
	Idle               int32 `protobuf:"varint,4,opt,name=Idle,proto3" json:"Idle,omitempty"`
	WaitCount          int32 `protobuf:"varint,5,opt,name=WaitCount,proto3" json:"WaitCount,omitempty"`
	WaitDuration       int32 `protobuf:"varint,6,opt,name=WaitDuration,proto3" json:"WaitDuration,omitempty"`
	MaxIdleClosed      int32 `protobuf:"varint,7,opt,name=MaxIdleClosed,proto3" json:"MaxIdleClosed,omitempty"`
	MaxIdleTimeClosed  int32 `protobuf:"varint,8,opt,name=MaxIdleTimeClosed,proto3" json:"MaxIdleTimeClosed,omitempty"`
	MaxLifetimeClosed  int32 `protobuf:"varint,9,opt,name=MaxLifetimeClosed,proto3" json:"MaxLifetimeClosed,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DatabaseInfo) Reset() {
	*x = DatabaseInfo{}
	mi := &file_infrastructure_grpc_proto_health_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseInfo) ProtoMessage() {}

func (x *DatabaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_grpc_proto_health_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseInfo.ProtoReflect.Descriptor instead.
func (*DatabaseInfo) Descriptor() ([]byte, []int) {
	return file_infrastructure_grpc_proto_health_proto_rawDescGZIP(), []int{4}
}

func (x *DatabaseInfo) GetMaxOpenConnections() int32 {
	if x != nil {
		return x.MaxOpenConnections
	}
	return 0
}

func (x *DatabaseInfo) GetOpenConnections() int32 {
	if x != nil {
		return x.OpenConnections
	}
	return 0
}

func (x *DatabaseInfo) GetInUse() int32 {
	if x != nil {
		return x.InUse
	}
	return 0
}

func (x *DatabaseInfo) GetIdle() int32 {
	if x != nil {
		return x.Idle
	}
	return 0
}

func (x *DatabaseInfo) GetWaitCount() int32 {
	if x != nil {
		return x.WaitCount
	}
	return 0
}

func (x *DatabaseInfo) GetWaitDuration() int32 {
	if x != nil {
		return x.WaitDuration
	}
	return 0
}

func (x *DatabaseInfo) GetMaxIdleClosed() int32 {
	if x != nil {
		return x.MaxIdleClosed
	}
	return 0
}

func (x *DatabaseInfo) GetMaxIdleTimeClosed() int32 {
	if x != nil {
		return x.MaxIdleTimeClosed
	}
	return 0
}

func (x *DatabaseInfo) GetMaxLifetimeClosed() int32 {
	if x != nil {
		return x.MaxLifetimeClosed
	}
	return 0
}

var File_infrastructure_grpc_proto_health_proto protoreflect.FileDescriptor

const file_infrastructure_grpc_proto_health_proto_rawDesc = "" +
	"\n" +
	"&infrastructure/grpc/proto/health.proto\x12\x06health\"\x15\n" +
	"\x13HealthMetricRequest\"t\n" +
	"\x14HealthMetricResponse\x12 \n" +
	"\x04meta\x18\x01 \x01(\v2\f.health.MetaR\x04meta\x121\n" +
	"\x04data\x18\x02 \x01(\v2\x18.health.HealthMetricDataH\x00R\x04data\x88\x01\x01B\a\n" +
	"\x05_data\"E\n" +
	"\x04Meta\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xbd\x01\n" +
	"\x10HealthMetricData\x12<\n" +
	"\x06status\x18\x01 \x03(\v2$.health.HealthMetricData.StatusEntryR\x06status\x120\n" +
	"\bdatabase\x18\x02 \x01(\v2\x14.health.DatabaseInfoR\bdatabase\x1a9\n" +
	"\vStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd6\x02\n" +
	"\fDatabaseInfo\x12.\n" +
	"\x12MaxOpenConnections\x18\x01 \x01(\x05R\x12MaxOpenConnections\x12(\n" +
	"\x0fOpenConnections\x18\x02 \x01(\x05R\x0fOpenConnections\x12\x14\n" +
	"\x05InUse\x18\x03 \x01(\x05R\x05InUse\x12\x12\n" +
	"\x04Idle\x18\x04 \x01(\x05R\x04Idle\x12\x1c\n" +
	"\tWaitCount\x18\x05 \x01(\x05R\tWaitCount\x12\"\n" +
	"\fWaitDuration\x18\x06 \x01(\x05R\fWaitDuration\x12$\n" +
	"\rMaxIdleClosed\x18\a \x01(\x05R\rMaxIdleClosed\x12,\n" +
	"\x11MaxIdleTimeClosed\x18\b \x01(\x05R\x11MaxIdleTimeClosed\x12,\n" +
	"\x11MaxLifetimeClosed\x18\t \x01(\x05R\x11MaxLifetimeClosed2]\n" +
	"\rHealthService\x12L\n" +
	"\x0fGetHealthMetric\x12\x1b.health.HealthMetricRequest\x1a\x1c.health.HealthMetricResponseB\x1eZ\x1cgo.risoftinc.com/xarch/protob\x06proto3"

var (
	file_infrastructure_grpc_proto_health_proto_rawDescOnce sync.Once
	file_infrastructure_grpc_proto_health_proto_rawDescData []byte
)

func file_infrastructure_grpc_proto_health_proto_rawDescGZIP() []byte {
	file_infrastructure_grpc_proto_health_proto_rawDescOnce.Do(func() {
		file_infrastructure_grpc_proto_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_infrastructure_grpc_proto_health_proto_rawDesc), len(file_infrastructure_grpc_proto_health_proto_rawDesc)))
	})
	return file_infrastructure_grpc_proto_health_proto_rawDescData
}

var file_infrastructure_grpc_proto_health_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_infrastructure_grpc_proto_health_proto_goTypes = []any{
	(*HealthMetricRequest)(nil),  // 0: health.HealthMetricRequest
	(*HealthMetricResponse)(nil), // 1: health.HealthMetricResponse
	(*Meta)(nil),                 // 2: health.Meta
	(*HealthMetricData)(nil),     // 3: health.HealthMetricData
	(*DatabaseInfo)(nil),         // 4: health.DatabaseInfo
	nil,                          // 5: health.HealthMetricData.StatusEntry
}
var file_infrastructure_grpc_proto_health_proto_depIdxs = []int32{
	2, // 0: health.HealthMetricResponse.meta:type_name -> health.Meta
	3, // 1: health.HealthMetricResponse.data:type_name -> health.HealthMetricData
	5, // 2: health.HealthMetricData.status:type_name -> health.HealthMetricData.StatusEntry
	4, // 3: health.HealthMetricData.database:type_name -> health.DatabaseInfo
	0, // 4: health.HealthService.GetHealthMetric:input_type -> health.HealthMetricRequest
	1, // 5: health.HealthService.GetHealthMetric:output_type -> health.HealthMetricResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_infrastructure_grpc_proto_health_proto_init() }
func file_infrastructure_grpc_proto_health_proto_init() {
	if File_infrastructure_grpc_proto_health_proto != nil {
		return
	}
	file_infrastructure_grpc_proto_health_proto_msgTypes[1].OneofWrappers = []any{}
	file_infrastructure_grpc_proto_health_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_infrastructure_grpc_proto_health_proto_rawDesc), len(file_infrastructure_grpc_proto_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_infrastructure_grpc_proto_health_proto_goTypes,
		DependencyIndexes: file_infrastructure_grpc_proto_health_proto_depIdxs,
		MessageInfos:      file_infrastructure_grpc_proto_health_proto_msgTypes,
	}.Build()
	File_infrastructure_grpc_proto_health_proto = out.File
	file_infrastructure_grpc_proto_health_proto_goTypes = nil
	file_infrastructure_grpc_proto_health_proto_depIdxs = nil
}
