// Code generated by Elsa. DO NOT EDIT.

//go:generate go run -mod=mod github.com/risoftinc/elsa/cmd/elsa gen
//go:build !elsabuild
// +build !elsabuild

package http

import (
	"github.com/risoftinc/elsa"

	config "github.com/risoftinc/xarch/config"
	gologger "github.com/risoftinc/gologger"
	gorm "gorm.io/gorm"
	healthHandler "github.com/risoftinc/xarch/infrastructure/grpc/handler/health"
	healthRepo "github.com/risoftinc/xarch/domain/repositories/health"
	healthSvc "github.com/risoftinc/xarch/domain/services/health"
	mid "github.com/risoftinc/xarch/infrastructure/grpc/middleware"
)

// This file generated from dep_manager.go at 2025-09-10T12:36:26+07:00

type Dependencies struct {
	Middlewares    mid.IContextMiddleware
	HealthHandlers healthHandler.HealthHandler
}

func InitializeServices(db *gorm.DB, cfg config.Config, logger gologger.Logger) *Dependencies {
	iHealthRepositories := healthRepo.NewHealthRepositories(db)
	iHealthServices := healthSvc.NewHealthService(logger, iHealthRepositories)
	healthHandler := healthHandler.NewHealthHandlers(logger, iHealthServices)
	iContextMiddleware := mid.NewContextMiddleware(logger)

	elsa.Generate(iHealthRepositories, iHealthServices, healthHandler, iContextMiddleware)
	return &Dependencies{
		Middlewares:    iContextMiddleware,
		HealthHandlers: *healthHandler,
	}
}

